### ISSUE TITLE
Inject SVG's in a bundle build

### ISSUE THREAD

**Issue by advename** [iconfu/svg-inject#19]
I'm also wondering if it's possible to make the SVG-inject available as a plugin for a bundler (e.g. ParcelJS) and upon bundling, the svg's are already injected.

This would be a big advantage as the bundled files already contain the SVG, and we don't need to use SVG-inject anymore to inject them every time.

**Comment by dasboe** [comment]
Agree, this is outside the scope of this project. Closing this issue.
