### ISSUE TITLE
'title' attribute not handled properly if namespaced title exists

### ISSUE THREAD

**Issue by waruyama** [iconfu/svg-inject#23]
Currently, if a `title` attribute is specified in the `<img>` element and the injected SVG already has a namespaced title element (for example `<svg:title>`, a new title element is created and inserted before the existing namespaced `<title>´ element. 

Instead the existing namespaced title element should be used and the content changed to the value of the `img`'s title attribute.

**Comment by waruyama** [comment]
Simple fix by using `localName` instead of `tagName`.

**Comment by iconfu** [comment]
just released Version 1.2.0 which fixes this issue
