### ISSUE TITLE
Empty SVGs on Internet Explorer

### ISSUE THREAD

**Issue by waruyama** [iconfu/svg-inject#3]
When injecting the same SVG multiple times, only the last one will be displayed on Internet Explorer. The other SVGs are empty, which means they have been injected, but the child elements are missing.

Everything works fine on Chrome and Firefox.

This issue is probably cause by this line: `DIV_ELEMENT.innerHTML = '';`

It seems this completely resolves the tree hierarchy for `DIV_ELEMENT`, removing also the children from the SVG element.

**Comment by dasboe** [comment]
fixed in 464641fa69437ed4e758fc9ba22fa12b788f2a54

is also faster because the old use of DIV_ELEMENT.innerHTML = ''; is slower then removing all child elements in a loop
