### ISSUE TITLE
Issue on page loading

### ISSUE THREAD

**Issue by PUShAUNE** [iconfu/svg-inject#34]
Hi,
The script works perfectly, but there is a thing that an be annoying.
On the page load, it seems that this script delay the .css
So, there is a quick moment without any style. You can see it on this video:
https://www.dropbox.com/s/g9wuh0llz1bnch3/issue_inject_svg.mov?dl=0

Is there any way to prevent that?

Thanks in advance.

**Comment by dasboe** [comment]
where do you include the script? Head?

**Comment by PUShAUNE** [comment]
Yep, before the </body> it works just fine. My mistake :(
Thank you!
