### ISSUE TITLE
Problem with title attribute.

### ISSUE THREAD

**Issue by berpcor** [iconfu/svg-inject#37]
I am using Twitter Bootstrap tooltip plugin. To show tooltip, it needs title attribute.
Your plugin copy contents of title attribute to title tag of svg and leaves nothing in attribute title.

Was:

`<img ... title="something"/>`

Become:

```
<svg ... title>
    <title>something</title>
...
</svg>
```

I need:

```
<svg ... title="something">
    <title>something</title>
...
</svg>
```

How to keep title value?

**Comment by dasboe** [comment]
you can find info about attribute handling here:

https://github.com/iconfu/svg-inject#how-are-attributes-handled
