### ISSUE TITLE
Unique ID for embedded SVGs

### ISSUE THREAD

**Issue by thanooshan** [iconfu/svg-inject#41]
Hi, is it possible to set unique ID for embedded SVGs?

**Comment by dasboe** [comment]
Could you please explain in detail, with example?

**Comment by thanooshan** [comment]
I mean inline SVGs, rather than linking with an `<img>` tag. Is it possible to change inlined SVGs ids.

**Comment by dasboe** [comment]
no, it's not possible with this tool

**Comment by waruyama** [comment]
@tanooshan The whole idea about SVGInject is to make external SVGs inline. There is no functionality to process SVGs that are already in the DOM.
