### ISSUE TITLE
Twice request

### ISSUE THREAD

**Issue by ionurboz** [iconfu/svg-inject#44]
## Option 1 - Call SVGInject from the onload attribute

Does this method cause the file to request twice?

**Comment by ionurboz** [comment]
@dasboe Thank you for the detailed explanation. Very good if all common browsers exhibit this behavior.

I am concerned about the browsers requesting from the server and then returning with the 304 status code. This way it will have an extra 150-300ms overhead (even if it doesn't download the file).

Of course, these are all assumptions. Very good as you said

**Comment by dasboe** [comment]
I've changed the README to address this Issue in [What are additional advantages when using onload??](https://github.com/iconfu/svg-inject/blob/master/README.md#what-are-additional-advantages-when-using-onload)
