### ISSUE TITLE
Does this work with React?

### ISSUE THREAD

**Issue by joshuarobs** [iconfu/svg-inject#46]
I'm trying to do something like:

````
import SVGInject from "@iconfu/svg-inject";

function Test() {
  return (
    <div>
             <img
                src={MySvg}
                onLoad={SVGInject(this)}
              />
    </div>
  );
}
````

Doesn't seem to be doing anything. I don't get an error, but the svg is still the same, and if I inspect it in console, it's still `img` instead of `svg`

**Comment by joshuarobs** [comment]
I replaced the `onLoad={SVGInject(this)}` with `onLoad={() => SVGInject(this)}` and it still does nothing. The error in the console tells me `no img element`

**Comment by Audreymlgm** [comment]
Hello @joshuarobs 

I try to do the same, did you find a solution ?
Thanks

**Comment by joshuarobs** [comment]
@Audreymlgm Nope, I'm not using this repo and I'm just using the `<svg>...</svg>` html tag

**Comment by JPYamamoto** [comment]
Just to let you know that `onLoad={(e) => SVGInject(e.srcElement)}` did the trick for me.

**Comment by chrisabrams** [comment]
> Just to let you know that `onLoad={(e) => SVGInject(e.srcElement)}` did the trick for me.

That didn't work for me, but `onLoad={(e) => SVGInject(e.target)}` did.

**Comment by Abdo-112002** [comment]
> > Just to let you know that `onLoad={(e) => SVGInject(e.srcElement)}` did the trick for me.
> 
> That didn't work for me, but `onLoad={(e) => SVGInject(e.target)}` did.

thanks my bro, I searched a lot to solve this problem
