### ISSUE TITLE
Css styles removed after injection

### ISSUE THREAD

**Issue by Salitehkat** [iconfu/svg-inject#60]
Good  morning, 
I noticed that any css style applied to the svg element (from a css stylesheet) is removed after  injection.  
Is there a way to prevent this? 
I have tried  loading the css file after the svg injection javascript file but without succes. 
Excuse my question if its too basic, and thanks very much for this plug in, 
Sali

Update: excuse  my question, my bad, I was attaching wrongly the css file.

**Comment by dasboe** [comment]
Glad you figured it out! Just in case anyone else lands here — CSS styles applied to the `<svg>` selector work fine after injection, just make sure the stylesheet is loaded and the selectors match the injected element (class names from the `<img>` are carried over automatically).
